---
title: "JapanR 2019 Conference Roundup"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# R for Beginners: An Overview!
[タナカケンタ](https://twitter.com/tanakafreelance)

# 始めてのLT 14:25~15:00


## Making life more convenient with R & Shiny!
自分が便利に生きるためにRとShinyを使う
発表者: kubota

- (also spoke at TokyoR Shiny session)
- Why: using at work,, want to check graphs and distribution of data
- use {plotly} >>> `plotly_click()`, `plotly_selected()` + {ggpairs}
- finding and exploring outlier values with CLICK functionality
- kind of slow and memory intensive....
- Still work-in-progress!


## Sports Analytics
スポーツ番狂わせの統計学
発表者: 窪田誠

- Ranking differences: When the league-leader loses against a relegation battler, etc.
- Probability of upsets based on team rankings
- Webscrape the data from Rugby World Rankings, Sumo, soccer, etc.
- Which sports have the most UPSETS??
-
-

## Using R for audio analytics
Rで音声解析をしてみる
発表者: 松本涼

- DTM: Desktop music >>>> DIY music production
- {tuneR} package >>>> Wave class (S4) objects
- {seewave}: visualize using amplittude and frequency plots, spectrograms

休憩＆ピックアップ&途中退出 15:00~15:20

# Long Talk - 20分枠 15:20~16:10

## Learning Data analysis with The Romance of the Three Kingdoms
三国志で学ぶデータ分析
発表者: ill-identified
[Slides](https://t.co/aDVHxpf5CS?amp=1)

- easy tutorial on a specific topic
- >> web-scraping, tiidyverse
- Three Kingdoms: Chinese historical fiction/fantasy
- what is true vs. fiction? lots that we don't know + fantasized
- Use stats from 3 Kingdoms videogame
- {rvest} >>> xpath
- messy tabular data: 
-- multiple skills/stats inside a single column....
-- data divided across two rows, empty columns, etc. 
- tidy with {tidyverse}
-- characters NOT shown via regular Japanese encoding...
- calculate by person >>> many characters with similar names, characters from OTHER series >>>> filter out 179 characters...
- ^ time to process manually >>> unsupervised learning
- image classification by converting names to bitmap then pixellize
-- use template matching {factoextra}
- DBpedia >>> SQARQL pkg
- {skimr}: show summary of large data set
- violin plot of certain attributes by series 
-
-


## Using meta-analysis to take a fair entrance exam
メタアナリシスっぽいので公平な入試を受けたい
発表者: med_ku
[Slides](https://t.co/S5UeBFZaLa?amp=1)

- News: University of Tokyo exams biased towards males??
- Fisher test for count data >>> Males vs. Female acceptance rate
-


休憩＆ピックアップ&途中退出 16:10 ~16:30


# Lightning Talk 16:30~18:20

## Visualizing JapanR Conference attendees
イベント参加者を可視化したい
発表者: doradora09

- organizer of Yakitori.R (Fukuoka R user group)
- scrape attendee data from event page
-- each user's groups
- word cloud: what other events have attnedees been to in the past??
- WHERE/which prefecture are attendees going to meetups?
- {VennDiagram}: visualize what communities/meetups have overlap
-- not just R but other languages (Pycon/PyDaa, Php)


## Using RStudio for Kaggle Competitions
KaggleとRStudioコンペの紹介
発表者: u++
[Slides](https://speakerdeck.com/upura/kaggle-r-competition)

- slack: kaggler-ja
- R competition on kaggle!
- machine learning modelling competition >> EDA + modeling >> refine model >> prize
- supervised/unsupervised learning >>> train + test data
- RStudio organizes a competition! >>> GA customer revenue prediction
-- https://www.kaggle.com/c/ga-customer-revenue-prediction/discussion/82614
-- https://www.kaggle.com/kostoglot/winning-solution#L144
- Google analytics data: user ID, session ID, device info, etc.
- ^ of analytics means simple analytics/modeling can be done by companies instead of sending to kaggle for solutions!
- Now more emphasis on looking deeper at the data where auto ML methods are weaker

## Visualizing the M-1 Grand Prix 
M-1グランプリ直前!?（直後!?）漫才の可視化に挑戦してみた
発表者: fujitako

- transcript of comedy shows
- MANUALLY gathered boke, tsukkomi, movement flags for own data set
- gganimate: movements of characters, boke/tsukkomi frequency bars 
- analyze HOW their jokes/stories unfold!
- see differences between different comedy groups!
- 
-
-

---
## 細菌叢のリアルワールドデータをビジネス活用するためのWebAPI作成
発表者: watanabe_st

- Why use Shiny?
- Synchronize with existing workflows
-

## The Tidyverse (Re)Explained
tidyverse（再）入門
発表者: 神沢雄大

- growth of the tidyverse, from introdcution of {dplyr} in 2014 + intro of {tidyverse} pkg in late 2016
- Base R native >>> tidyverse native
- ex. rewrite old code into the tidyverse


## Using {tidymodels} for tidy machine learning!
tidymodelsによるtidyな機械学習
発表者: morishita(@dropout0009)

- {rsample}, {recipe}, {parsnip}, {tune}, {yardstic}
- Example: use {AmesHousing} data set
- train/test >>>> cross validation `vfold_cv()`
- `recipe()` >> `step_log()`
- `parsnip::rand_forest()`, `set_engine()` to set WHICH RF pkg to use
- {tune}: tuning hyperparameters
- `prep()`, `juice()`, `bake()`
- check test data accuracy/precision with {yardstic}

## Database Queries with R
データサイエンティストに同じクエリは二度も通じぬ
発表者: Takahiro Yoshinaga
[Slides](https://speakerdeck.com/yoshinaga0106/detasaienteisutonitong-zikuerihaer-du-motong-zinu)

- advertisement data
- copy-paste `summarize()` code
- {mmetrics} data analysis
- aggregates/disaggregates
- set/define metrics via `define()`


## Using Java with R
Rで書くJava仮想マシン (R上でJavaを動かしてみた)
発表者: @igjit
[Slides](https://igjit.github.io/slides/2019/12/jvmrr/#/)

- Java virtual machine, can use Java ANYWHERE 
- create Java VM with R >>> {jvmrr}
- compile Java code >>> then import into R and execute!
- {purrr}: list of lists for functions


## Using Apache Arrow with R
Apache Arrowについて（仮）
発表者: yutannihilation

- on-memory big data handling platform
- define a data format for on-memory 
- need Apache Arrow: LESSEN need for copy-convert data
- {Parquet}, {Feather} >>> {arrow }
- {sparklyr} >>> Spark 
- Apache Parquet >>> data format
- FAST data import!
- dplyr backend?


----
## 未定
発表者: ymn753

- "We would like the data in EXCEL :D XD" ...
- interactive data analysis 
- >>> {DataTable}, {DT} pkg, {reactable}, rpivottable, rhandsontable, etc.
- R port of React Table JS library 
-


## Regression analysis using R
発表者: はしもん

- 
-


## Causal Inference with R
今再びのRによる因果推論
発表者: nino_pira

- 
-
-

## MCMC with R
グレブナー基底でMCMC
発表者: kyusque
[repo](https://github.com/kyusque/japanr2019)

- Running MCMC with Groebner basis
-
-

## Baseball analytics with R
野球ネタで何か
発表者: @flaty13
[Slides](https://docs.google.com/presentation/d/1E3Sop2VK1-F4T2dVBMgxJgMRPyNXz1XJfAkpX7UfN-0/edit)

- Analyzing Baseball data with R (M. Marchi, J. Albert)
- how would title race look if every team were of equal strength/ability 
-- 0.546/0.564 win % == highly possible?
- a win for one team == loss for another, NOT independent
-


## 身近なものをデータにしてサイエンスする
発表者: 市川太祐

- noh flute sound >>> spectrogram
- comparison of sound quality-
-

## Rのコミュニティを始めた話
発表者: @tachyon7776

- Building an R Community!
- no R community in Tohoku region!! 
- suggestion? why not create one?
- help from social media >> twitter
- finding a place to host... difficult!
- guest speakers from other regions


## このIRのグラフがすごい！上場企業2019
発表者: ito_yan

- bad visualization techniques from company revenue reports
- awful pie graphs
- deliberate obfuscation of data points
- double-axis bar plots
- 
-
-
-

